language: java
sudo: required
services:
  - docker

before_install:
  - docker build -t hyde009/hml -f ./hml-ronswanson-quotes/Dockerfile.withbuild .

scripts:
  - docker run hyde009/hml mvn test -- --coverage